#!/bin/bash
#set -x
app=$(dirname $(realpath $0))
action=usage
option=''
V=0
dirChecked=''
limit=''
coffee=()

verbose() {
    if [ "$1" -le "$V" ]; then
        shift
        echo "$@" 1>&2
    fi
}

checkDir() {
    if [ -z "$dirChecked" ]; then
        if [ -z "$dir" ]; then
            usage "No directory given"
        fi
        cd "$dir"
        dirChecked=true
    fi
}

coffee() {
    checkDir
    exec coffee $(cygpath -w "$app/watch.coffee") "${coffee[@]}" .
}

scrub() {
    checkDir
    rm -f ".indexer"
}

prefixSearch() {
    checkDir
    verbose 1 Search pattern: "$pattern", dir: "$dir"
    sqlite3 .indexer "select file || ':' || line_number || ':' || line from lines where line match '$pattern*' $limit"
}

middleSearch() {
    checkDir
    verbose 1 Search pattern: "$pattern", dir: "$dir"
    cmd=''
    terms=$(sqlite3 .indexer "select term from lines_terms where term glob '*$pattern*'")
    for t in $terms; do
        if [ -n "$cmd" ]; then
            cmd="$cmd union select rowid, file, line_number, line from lines where line match '$t'"
        else
            cmd="select rowid, file, line_number, line from lines where line match '$t'"
        fi
    done
    if [ -n "$terms" ]; then
        #echo SQL: "$cmd"
        echo TERMS: $terms
        sqlite3 .indexer "select file || ':' || line_number || ':' || line from ($cmd) group by rowid order by rowid $limit"
    else
        echo NO TERMS
    fi
}

callers() {
    checkDir
    sqlite3 .indexer "select coffee.file || ':' || coffee.line || ':' || col || ':' || code || ':' || lines.line from coffee, lines where call = '$func' and coffee.file = lines.file and coffee.line = lines.line_number order by coffee.rowid"
}

callees() {
    checkDir
    sqlite3 .indexer "select coffee.file || ':' || coffee.line || ':' || col || ':' || code || ':' || call || ':' || lines.line from coffee, lines where code = '$func' and coffee.file = lines.file and coffee.line = lines.line_number order by coffee.rowid"
}

funcs() {
    checkDir
    sqlite3 .indexer "select code from coffee group by code order by rowid"
}

setAction() {
    if [ -n "$option" ]; then
        usage "Attempt to use two actions at once, $option and $1"
    fi
    option=$1
    action=$2
}

processArgs() {
    while [ "$#" != 0 ]; do
        case "$1" in
            -h)
                usage
                ;;
            -d)
                setAction -d scrub
                ;;
            -p)
                setAction -p prefixSearch
                pattern="$2"
                shift
                ;;
            -s)
                setAction -p middleSearch
                pattern="$2"
                shift
                ;;
            -i)
                coffee[${#coffee[*]}]=-i
                coffee[${#coffee[*]}]="$2"
                shift
                ;;
            -v)
                V=$((V + 1))
                coffee[${#coffee[*]}]=-v
                ;;
            -q)
                coffee[${#coffee[*]}]=-q
                ;;
            -n)
                coffee[${#coffee[*]}]=-n
                ;;
            -l)
                limit="limit $2 offset $3"
                shift
                shift
                ;;
            -m)
                setAction -m coffee
                ;;
            -u)
                coffee[${#coffee[*]}]=-u
                setAction -u coffee
                ;;
            -c)
                coffee[${#coffee[*]}]=-c
                ;;
            --callers)
                setAction --callers callers
                func="$2"
                shift
                ;;
            --callees)
                setAction --callees callees
                func="$2"
                shift
                ;;
            --funcs)
                setAction --funcs funcs
                ;;
            -*)
                usage "Unknown argument: $1"
                ;;
            *)
                dir="$1"
                ;;
        esac
        shift
    done
    if [ -n "$coffee" -a "$action" != "coffee" ]; then
        usage "Options require -u or -m"
    fi
}

usage() {
    if [ $# != 0 ]; then
        echo $*
        echo
    fi
    cat <<EOF
Usage: $(basename $0) [-h | -d | -s PATTERN | -m | -u] [DIR]
DIR is the directory containing the files to index.
If DIR is given, a new ".indexer" database is created
in DIR if it does not exist
OPTIONS:
  -h            Print this message
  -d            Delete the .indexer database
  -i PATTERN    Ignore files matching pattern
  -s PATTERN    Search for token pattern in files and return matched lines in grep format
  -p PATTERN    Search for prefix token pattern in files and return matched lines in grep format
  -l LIM OFF    Limit the number of search results to LIM and discard the first OFF
  -t PATTERN    Find all tokens matching pattern
  -v            Inccrease verbosity
  -q            Turn off progress notifications
  -n            Notify of changes (implies -q): 'DELETE'|'CREATE'|'MODIFY' FILE
  -u            Update
  -m            Update and continue monitoring for changes
  -c            Index CoffeeScript callers and callees
  --callers F   List call sites of F: FILE:LINE:COL:FUNC
  --callee F    List F's call sites: FILE:LINE:COL:FUNC
EOF
    exit 1
}

processArgs "$@"
$action
