#!/bin/bash
#set -x
app=$(dirname $(realpath $0))
action=usage
option=''
V=0
dirChecked=''
limit=''
coffee=()
parent="defs.parent = ''"
all=''
localcalls=''

verbose() {
    if [ "$1" -le "$V" ]; then
        shift
        echo "$@" 1>&2
    fi
}

checkDir() {
    if [ -z "$dirChecked" ]; then
        if [ -z "$dir" ]; then
            usage "No directory given"
        fi
        cd "$dir"
        dirChecked=true
    fi
}

coffee() {
    checkDir
    exec coffee $(cygpath -w "$app/watch.coffee") "${coffee[@]}" .
}

scrub() {
    checkDir
    rm -f ".sourcecodex"
}

prefixSearch() {
    checkDir
    verbose 1 Search pattern: "$pattern", dir: "$dir"
    sqlite3 .sourcecodex "select file || ':' || line_number || ':' || line from lines where line match '$pattern*' $limit"
}

middleSearch() {
    checkDir
    verbose 1 Search pattern: "$pattern", dir: "$dir"
    cmd=''
    terms=$(sqlite3 .sourcecodex "select term from lines_terms where term glob '*$pattern*'")
    for t in $terms; do
        if [ -n "$cmd" ]; then
            cmd="$cmd union select rowid, file, line_number, line from lines where line match '$t'"
        else
            cmd="select rowid, file, line_number, line from lines where line match '$t'"
        fi
    done
    if [ -n "$terms" ]; then
        #echo SQL: "$cmd"
        echo TERMS: $terms
        sqlite3 .sourcecodex "select file || ':' || line_number || ':' || line from ($cmd) group by rowid order by rowid $limit"
    else
        echo NO TERMS
    fi
}

setLocal() {
    parent="(defs.parent = '' or defs.parent = '$1')"
}

callers() {
    checkDir
    sqlite3 .sourcecodex "select calls.file || ':' || calls.line_number || ':' || calls.col || ':' || calls.code || ':' || line from calls, lines, defs where calls.file = lines.file and calls.line_number = lines.line_number and call = '$func' and defs.code = calls.code and $parent and exists (select * from defs where code = '$func' and $parent) order by calls.rowid"
}

allCalls() {
    checkDir
    sqlite3 .sourcecodex "select calls.file || ':' || calls.line_number || ':' || calls.col || ':' || calls.code || ':' || call || ':' || line from calls, lines where calls.file = lines.file and calls.line_number = lines.line_number order by calls.rowid"
}

calls() {
    checkDir
    if [ -n "$localcalls" ]; then
        setLocal "$func"
    fi
    sqlite3 .sourcecodex "select calls.file || ':' || calls.line_number || ':' || calls.col || ':' || calls.code || ':' || call || ':' || line from calls, lines, defs where calls.file = lines.file and calls.line_number = lines.line_number and defs.code = call and calls.code = '$func' and $parent order by calls.rowid"
}

allDefs() {
    checkDir
    sqlite3 .sourcecodex "select file || ':' || line_number || ':' || col || ':' || type || ':' || code || ':' || parent || ':' || line from defs, lines using(file,line_number) order by defs.rowid"
}

defs() {
    checkDir
    sqlite3 .sourcecodex "select file || ':' || line_number || ':' || col || ':' || type || ':' || code || ':' || parent || ':' || line from defs, lines using(file,line_number) where $parent order by defs.rowid"
}

setAction() {
    if [ -n "$option" ]; then
        usage "Attempt to use two actions at once, $option and $1"
    fi
    option=$1
    action=$2
}

processArgs() {
    while [ "$#" != 0 ]; do
        case "$1" in
            -h)
                usage
                ;;
            -d)
                setAction -d scrub
                ;;
            -p)
                setAction -p prefixSearch
                pattern="$2"
                shift
                ;;
            -s)
                setAction -p middleSearch
                pattern="$2"
                shift
                ;;
            -i)
                coffee[${#coffee[*]}]=-i
                coffee[${#coffee[*]}]="$2"
                shift
                ;;
            -v)
                V=$((V + 1))
                coffee[${#coffee[*]}]=-v
                ;;
            -q)
                coffee[${#coffee[*]}]=-q
                ;;
            -n)
                coffee[${#coffee[*]}]=-n
                ;;
            -l)
                limit="limit $2 offset $3"
                shift
                shift
                ;;
            -m)
                setAction -m coffee
                ;;
            -u)
                coffee[${#coffee[*]}]=-u
                setAction -u coffee
                ;;
            -r)
                coffee[${#coffee[*]}]=-r
                ;;
            -c)
                coffee[${#coffee[*]}]=-c
                ;;
            -j)
                coffee[${#coffee[*]}]=-j
                ;;
            -a)
                all='true'
                ;;
            --parent)
                parent="(defs.parent = '' or defs.parent = '$2')"
                shift
                ;;
            --allcalls)
                setAction --allcalls allCalls
                ;;
            --localcalls)
                setAction --localcalls calls
                func="$2"
                localcalls=true
                ;;
            --callers)
                setAction --callers callers
                func="$2"
                shift
                ;;
            --calls)
                setAction --calls calls
                func="$2"
                shift
                ;;
            --alldefs)
                setAction --alldefs allDefs
                ;;
            --defs)
                setAction --defs defs
                ;;
            -*)
                usage "Unknown argument: $1"
                ;;
            *)
                dir="$1"
                ;;
        esac
        shift
    done
    if [ -n "$coffee" -a "$action" != "coffee" ]; then
        usage "Options require -u or -m"
    fi
}

usage() {
    if [ $# != 0 ]; then
        echo $*
        echo
    fi
    cat <<EOF
Usage: $(basename $0) [ -h | -i PATTERN | -s PATTERN | -p PATTERN | -l LIM OFF | -t PATTERN | -v | -q | -n | -d | -r | -u | -m | -c | -j | --parent F | --callers F | --calls F | --localcalls F | --allcalls | --defs | --alldefs ] [DIR]
DIR is the directory containing the files to index.
If DIR is given, a new ".sourcecodex" database is created
in DIR if it does not exist
OPTIONS:
  -h            Print this message
  -i PATTERN    Ignore files matching pattern
  -s PATTERN    Search for token pattern in files and return matched lines in grep format
  -p PATTERN    Search for prefix token pattern in files and return matched lines in grep format
  -l LIM OFF    Limit the number of search results to LIM and discard the first OFF
  -t PATTERN    Find all tokens matching pattern
  -v            Inccrease verbosity
  -q            Turn off progress notifications
  -n            Notify of changes (implies -q): 'DELETE'|'CREATE'|'MODIFY' FILE
  -d            Delete the .sourcecodex database
  -r            Delete and rebuild database
  -u            Update and then exit
  -m            Update and continue monitoring for changes
  -c            Index CoffeeScript callers and calls
  -j            Index JavaScript callers and calls
  --parent F    Set parent for callers/calls/defs search
  --callers F   List call sites of F: FILE:LINE:COL:FUNC:CONTENTS
  --calls F     List F's call sites: FILE:LINE:COL:FUNC:CONTENTS
  --localcalls F Shorthand for --calls F --parent F
  --allcalls    List all calls in the project
  --defs        List defs: FILE:LINE:COL:FUNC:CONTENTS
  --alldefs     List all defs in the project
EOF
    exit 1
}

processArgs "$@"
$action
